sudo: false
services: mongodb
language: python
python:
  - "2.7"
  - "3.5"
  - "pypy"
env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11.2
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install -q Django==$DJANGO_VERSION
# command to run tests
script: python setup.py -q nosetests
